# -*- coding: utf-8 -*-
"""Mexicanhatfuzzyset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trYV0Oew-3whrjhCjitRO6hdOi4DEOvT
"""

import numpy as np
import matplotlib.pyplot as plt

class MexicanFuzzySet:
  def __init__(self, c, sigma):
    self.c = c
    self.sigma = sigma
  def membership(self, x):
    value = (1 - ((x - self.c)**2 / self.sigma**2)) * (np.exp(-((x-self.c)**2) /(2 * self.sigma**2)))
    return max(0, value)

  def area(self):
    return self.sigma * np.sqrt(2 * np.pi)

temperature_below_average = MexicanFuzzySet(30, 8)
temperature_low = MexicanFuzzySet(10, 7)

pressure_below_average = MexicanFuzzySet(2, 0.4)
pressure_low = MexicanFuzzySet(1, 0.4)

heating_power_medium_high = MexicanFuzzySet(4, 0.4)
heating_power_high = MexicanFuzzySet(5, 0.4)

valve_opening_medium_low = MexicanFuzzySet(2, 0.4)
valve_opening_small = MexicanFuzzySet(1, 0.4)

temperature_input = 16.5
pressure_input = 1.3

z1 = min(
    temperature_below_average.membership(temperature_input),
    pressure_below_average.membership(pressure_input)
)

z2 = min(
    temperature_low.membership(temperature_input),
    pressure_low.membership(pressure_input)
)

print(f"z1: {z1}")
print(f"z2: {z2}")

c1num = (z1 * heating_power_medium_high.area() * heating_power_medium_high.c) + \
  (z2 * heating_power_high.area() * heating_power_high.c)

c2num = (z1 * valve_opening_medium_low.area() * valve_opening_medium_low.c) + \
        (z2 * valve_opening_small.area() * valve_opening_small.c)

c1den = (z1 * heating_power_medium_high.area()) +\
        (z2 * heating_power_high.area())

c2den = (z1 * valve_opening_medium_low.area()) +\
        (z2 * valve_opening_small.area())


c1 = c1num / c1den
c2 = c2num / c2den

print("C1 and C2:",c1,c2)

x_hp = np.linspace(2.5, 6, 500)
mh = np.array([heating_power_medium_high.membership(x) for x in x_hp])
h = np.array([heating_power_high.membership(x) for x in x_hp])

plt.figure(figsize=(8,4))
plt.plot(x_hp, mh, label="Medium High")
plt.plot(x_hp, h, label="High")
plt.fill_between(x_hp, 0, np.minimum(mh, z1), alpha=0.4)
plt.fill_between(x_hp, 0, np.minimum(h, z2), alpha=0.4)
plt.axvline(c1, linestyle="--", label=f"C1 = {c1:.2f}")
plt.xlabel("Heating Power")
plt.ylabel("Membership")
plt.title("Heating Power Output (Mexican Hat)")
plt.legend()
plt.grid(True)
plt.show()

x_vo = np.linspace(0, 3, 500)
ml = np.array([valve_opening_medium_low.membership(x) for x in x_vo])
s = np.array([valve_opening_small.membership(x) for x in x_vo])

plt.figure(figsize=(8,4))
plt.plot(x_vo, ml, label="Medium Low")
plt.plot(x_vo, s, label="Small")
plt.fill_between(x_vo, 0, np.minimum(ml, z1), alpha=0.4)
plt.fill_between(x_vo, 0, np.minimum(s, z2), alpha=0.4)
plt.axvline(c2, linestyle="--", label=f"C2 = {c2:.2f}")
plt.xlabel("Valve Opening")
plt.ylabel("Membership")
plt.title("Valve Opening Output (Mexican Hat)")
plt.legend()
plt.grid(True)
plt.show()