# -*- coding: utf-8 -*-
"""MultilayerPerceptron using IRIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PzqI9muPSU7kDPXxyqX3KjGWngLyeJ2A
"""

# Commented out IPython magic to ensure Python compatibility.
from random import seed
from random import random
from random import randrange
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
import math

iris = load_iris()

X = iris.data
y = iris.target

def initialize_network(n_inputs, n_hidden, n_outputs):
    network = list()
    hidden_layer = [{'weights': [random() for i in range(n_inputs + 1)]} for i in range(n_hidden)]
    network.append(hidden_layer)
    output_layer = [{'weights': [random() for i in range(n_hidden + 1)]} for i in range(n_outputs)]
    network.append(output_layer)
    return network

seed(1)
new_structure = initialize_network(4, 1, 3)

def activate(weights, inputs):
    activation = weights[-1]
    for i in range(len(weights) - 1):
        activation += weights[i] * inputs[i]
    return activation

def transfer(activation):
    return 1.0 / (1.0 + math.exp(-activation))

def forward_propagate(network, row):
    inputs = row
    for layer in network:
        new_inputs = []
        for neuron in layer:
            activation = activate(neuron['weights'], inputs)
            neuron['output'] = transfer(activation)
            new_inputs.append(neuron['output'])
        inputs = new_inputs
    return inputs

def transfer_derivative(output):
    return output * (1.0 - output)

def backward_propagate_error(network, expected):
    for i in reversed(range(len(network))):
        layer = network[i]
        errors = []
        if i != len(network) - 1:
            for j in range(len(layer)):
                error = 0.0
                for neuron in network[i + 1]:
                    error += neuron['weights'][j] * neuron['delta']
                errors.append(error)
        else:
            for j in range(len(layer)):
                errors.append(layer[j]['output'] - expected[j])
        for j in range(len(layer)):
            layer[j]['delta'] = errors[j] * transfer_derivative(layer[j]['output'])

def update_weights(network, row, l_rate):
    for i in range(len(network)):
        inputs = row[:-1]
        if i != 0:
            inputs = [neuron['output'] for neuron in network[i - 1]]
        for neuron in network[i]:
            for j in range(len(inputs)):
                neuron['weights'][j] -= l_rate * neuron['delta'] * inputs[j]
            neuron['weights'][-1] -= l_rate * neuron['delta']

seed(1)

def train_network(dataset, l_rate, n_epoch, n_outputs, n_hidden, n_folds):

    dataset_copy = list(dataset)
    folds = []
    fold_size = int(len(dataset) / n_folds)

    for _ in range(n_folds):
        fold = []
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        folds.append(fold)

    scores = []

    for fold_idx, fold in enumerate(folds):

        train_set = []
        for f in folds:
            if f is not fold:
                train_set.extend(f)

        test_set = [list(row) for row in fold]
        network = initialize_network(4, n_hidden, n_outputs)

        for epoch in range(n_epoch):
            sum_error = 0
            for row in train_set:
                outputs = forward_propagate(network, row[:-1])
                expected = [0 for i in range(n_outputs)]
                expected[row[-1]] = 1
                sum_error += sum((expected[i] - outputs[i]) ** 2 for i in range(len(expected)))
                backward_propagate_error(network, expected)
                update_weights(network, row, l_rate)

            print('Fold %d, Epoch=%d, lrate=%.3f, error=%.3f'
#                   % (fold_idx + 1, epoch, l_rate, sum_error))

        predicted = []
        actual = []
        for row in test_set:
            outputs = forward_propagate(network, row[:-1])
            predicted.append(outputs.index(max(outputs)))
            actual.append(row[-1])

        fold_accuracy = sum(1 for i in range(len(actual)) if actual[i] == predicted[i]) / len(actual) * 100
        scores.append(fold_accuracy)
        print(f'Fold {fold_idx + 1} Accuracy: {fold_accuracy:.2f}%\n')

    print(f'Mean Accuracy: {sum(scores) / len(scores):.2f}%')

    cm = confusion_matrix(actual, predicted)
    sns.heatmap(cm, annot=True, fmt='g', cmap = 'Blues')
    plt.ylabel('Actual')
    plt.xlabel('Prediction')
    plt.title('Confusion Matrix')
    plt.show()

dataset = [list(X[i]) + [y[i]] for i in range(len(X))]

train_network(
    dataset=dataset,
    l_rate=0.3,
    n_epoch=1000,
    n_outputs=3,
    n_hidden=5,
    n_folds=5
)

