# -*- coding: utf-8 -*-
"""rbf1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1arwAjWBvjZHFd8nvcjfzuvX48PEfOoQs
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.cluster import DBSCAN
import math

df = pd.read_csv("bank.csv")

x_numeric = df[['age', 'balance', 'day', 'duration',
                'campaign', 'pdays', 'previous']]

x_categorical = df[['job', 'marital', 'education', 'default',
                    'housing', 'loan', 'contact', 'month',
                    'poutcome', 'deposit']]

le = LabelEncoder()
x_categorical = x_categorical.apply(le.fit_transform)

new_df = pd.concat([x_numeric, x_categorical], axis=1)

data_train, data_test = train_test_split(
    new_df, test_size=0.5, random_state=42
)

x_train = data_train.drop('deposit', axis=1)
y_train = data_train['deposit']

x_test = data_test.drop('deposit', axis=1)
y_test = data_test['deposit']

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# DBSCAN for centers
db = DBSCAN(eps=1.5, min_samples=5)
labels = db.fit_predict(x_train)
unique_labels = set(labels) - {-1}

cent = np.array([x_train[labels == label].mean(axis=0) for label in unique_labels])

def tps_rbf(r):
    if r == 0:
        return 0
    return r**2 * math.log(r)

row = x_train.shape[0]
column = cent.shape[0]
G = np.empty((row, column), dtype=float)

for i in range(row):
    for j in range(column):
        distance = math.dist(x_train[i], cent[j])
        G[i][j] = tps_rbf(distance)

GTG = np.dot(G.T, G)
GTG_inv = np.linalg.inv(GTG)
fac = np.dot(GTG_inv, G.T)
W = np.dot(fac, y_train)

row = x_test.shape[0]
G_t = np.empty((row, column), dtype=float)

for i in range(row):
    for j in range(column):
        distance = math.dist(x_test[i], cent[j])
        G_t[i][j] = tps_rbf(distance)

prediction = np.dot(G_t, W)
y_pred = (prediction >= prediction.mean()).astype(int)

accuracy = (y_pred == y_test.values).mean()
print("Accuracy:", accuracy)